name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "django_app/**"
      - "todo/**"

jobs:
  pytest-chiron-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        run: source scripts/pytest-app.sh